export const LOGIN_EMPLOYEE = 'LOGIN_EMPLOYEE';
export const REGISTER_EMPLOYEE = 'REGISTER_EMPLOYEE';
export const SET_ERROR_LOGIN_MESSAGE = 'SET_ERROR_LOGIN_MESSAGE';
export const SET_ERROR_REGISTER_MESSAGE = 'SET_ERROR_REGISTER_MESSAGE';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';