export const GET_STATIONS = 'GET_STATIONS';
export const DELETE_STATION = 'DELETE_STATION';
export const ADD_STATION = 'ADD_STATION';
export const SET_ADD_STATION_SUCCESS_MESSAGE = 'SET_ADD_STATION_SUCCESS_MESSAGE';
export const SET_ADD_STATION_ERROR_MESSAGE = 'SET_ADD_STATION_ERROR_MESSAGE';